{{ config(
    materialized = 'table',
    catalog_name  = 'bigquery_iceberg_catalog'
) }}

select 
    000 as _meta_load_id,
    '{{ run_started_at }}' as _meta_load_timestamp,
    'colorado_companies' as _meta_load_name,
    '1.0.0' as _meta_load_version,
    'METADATA$FILENAME' as _meta_stg_file_name,
    'METADATA$FILE_LAST_MODIFIED 'as _meta_stg_file_last_modified,
    'METADATA$FILE_ROW_NUMBER' as _meta_stg_file_row_number,
    'METADATA$FILE_CONTENT_KEY' AS _meta_stg_file_hash,
    'us_colorado' as _meta_source_system,
    '' as _meta_source_entity,
    'US' as _meta_country,
    'us_colorado' as _meta_jurisdiction,
    '' as _meta_registration_authority_code,
    entityid as entity_id,
    entityname as entity_name,
    principaladdress1 as principal_address_1,
    principaladdress2 as principal_address_2,
    principalcity as principal_city,
    principalstate as principal_state,
    principalzipcode as principal_zipcode,
    principalcountry as principal_country,
    mailingaddress1 as mailing_address_1,
    mailingaddress2 as mailing_address_2,
    mailingcity as mailing_city,
    mailingstate as mailing_state,
    mailingzipcode as mailing_zipcode,
    mailingcountry as mailing_country,
    entitystatus as entity_status,
    jurisdictonofformation as jurisdiction_of_formation,
    entitytype as entity_type,
    agentfirstname as agent_first_name,
    agentmiddlename as agent_middle_name,
    agentlastname as agent_last_name,
    agentsuffix as agent_suffix,
    agentorganizationname as agent_organization_name,
    agentprincipaladdress1 as agent_principal_address_1,
    agentprincipaladdress2 as agent_principal_address_2,
    agentprincipalcity as agent_principal_city,
    agentprincipalstate as agent_principal_state,
    agentprincipalzipcode as agent_principal_zipcode,
    agentprincipalcountry as agent_principal_country,
    agentmailingaddress1 as agent_mailing_address_1,
    agentmailingaddress2 as agent_mailing_address_2,
    agentmailingcity as agent_mailing_city,
    agentmailingstate as agent_mailing_state,
    agentmailingzipcode as agent_mailing_zipcode,
    agentmailingcountry as agent_mailing_country,
    entityformdate as entity_form_date
from {{ source('eix_staging', 'stg_eix_colorado_ext') }}
