name: 'oc_data_dbt'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'oc_data_dbt'

# These configurations specify where dbt should look for different types of files.

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:  # This setting specifies which directories dbt should clean when you run `dbt clean`.
  - "target"
  - "dbt_packages"

# Configuring models
models:
  raw:
    +materialized: table
    +tags: ["raw"]
  rdv:
    +materialized: view
    +tags: ["rdv"]
  staging:
    +materialized: view
    +tags: ["staging"]

models:
  transient: false

  # Our project
  oc_data_dbt:
    ## Layer - Raw
    raw:
        +database: oc_dw_dev
        +schema: oc_staging
        +materialized: view

    ## Layer - Staging
    staging:
        +database: oc_dw_dev
        +schema: oc_staging
        +materialized: table

    ## Layer - RDV
    rdv:
        +database: oc_dw_dev
        +schema: oc_rdv
        +materialized: incremental

    ## Layer - Analytics
    analytics:
        +database: oc_dw_dev
        +schema: oc_conformed_back_sync
        +materialized: incremental
